'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class RecursosPle
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GeneradorCod.RecursosPle", GetType(RecursosPle).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO CampoComponentes VALUES (@MyIDPlantilla,&apos;Tipo&apos;,&apos;Prefijo&apos;,&apos;Superior&apos;,&apos;Sufijo&apos;,&apos;Inferior&apos;,&apos;SeparadorCampos&apos;,&apos;MultiReplace&apos;,@MyIDComponente,&apos;FormatoCampo&apos;).
        '''</summary>
        Friend Shared ReadOnly Property Campos() As String
            Get
                Return ResourceManager.GetString("Campos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO Componentes VALUES(@MyIDPlantilla,&apos;NombreComponente&apos;,&apos;Codigo&apos;,&apos;XTabla&apos;,&apos;XBase&apos;,&apos;Dependiente&apos;).
        '''</summary>
        Friend Shared ReadOnly Property Componente() As String
            Get
                Return ResourceManager.GetString("Componente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT INTO Plantillas VALUES (@MyIDTecnologia,&apos;nombrePlantilla&apos;,Orden,&apos;Seleccionada&apos;);.
        '''</summary>
        Friend Shared ReadOnly Property Plantilla() As String
            Get
                Return ResourceManager.GetString("Plantilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SET @MyIDComponente =  (SELECT MAX(ComponenteID) FROM Componentes).
        '''</summary>
        Friend Shared ReadOnly Property SeteoIDComponente() As String
            Get
                Return ResourceManager.GetString("SeteoIDComponente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SET @MyIDPlantilla =  (SELECT MAX(PlantillaID) FROM Plantillas).
        '''</summary>
        Friend Shared ReadOnly Property SeteoIDPlantilla() As String
            Get
                Return ResourceManager.GetString("SeteoIDPlantilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SET @MyIDTecnologia =  (SELECT MAX(TecnologiaID) FROM Tecnologias).
        '''</summary>
        Friend Shared ReadOnly Property SeteoIDTecnologia() As String
            Get
                Return ResourceManager.GetString("SeteoIDTecnologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --DECLARACION DE VARIABLES
        '''DECLARE @MyIDTecnologia INT;
        '''DECLARE @MyIDPlantilla INT; 
        '''DECLARE @MyIDComponente INT; 
        '''--TECNOLOGIA
        '''INSERT INTO Tecnologias VALUES (&apos;nombreDeLaTecnologia&apos;,&apos;True&apos;);.
        '''</summary>
        Friend Shared ReadOnly Property Tecnologia() As String
            Get
                Return ResourceManager.GetString("Tecnologia", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
