//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorCodigoAdm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecn_bloque_codigo
    {
        public int BloqueID { get; set; }
        public int TecnologiaID { get; set; }
        public string NombreBloque { get; set; }
        public string Contenido { get; set; }
    
        public virtual tecn_tecnologias tecn_tecnologias { get; set; }
    }
}
