//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorCodigoAdm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecn_tecnologias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tecn_tecnologias()
        {
            this.tecn_bloque_codigo = new HashSet<tecn_bloque_codigo>();
        }
    
        public int TecnologiaID { get; set; }
        public string NombreTecnologia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tecn_bloque_codigo> tecn_bloque_codigo { get; set; }
    }
}
